- name: Running scripts to configure the web server
  hosts: tag_type_webserver
  sudo: yes
  gather_facts: False
  tasks:
    - name: apt-get update the server
      apt: update_cache=yes
    
    - name: apt-get install git
      apt: name=git-core state=latest
      
    - name: remove src directory if it exists
      file: path=/src state=absent
      
    - name: create src directory
      file: path=/src state=directory
    
    - name: use git to pull scripts
      git: repo=https://github.com/TeamOSO/DevOps-Challenge.git clone=yes dest=/src accept_hostkey=yes
      
    - name: Run common setup script on web servers
      sudo: yes
      shell: /src/Install-Scripts/common.sh
