- name: Running scripts to configure the web server
  hosts: tag_type_webserver
  sudo: yes
  gather_facts: False
  tasks:
    - name: apt-get update the server
      apt: update_cache=yes
      
    - name: Run common setup script on web servers
      script: ../Install-Scripts/common.sh
