- name: Running scripts to configure the web server
  hosts: ec2-52-11-79-82.us-west-2.compute.amazonaws.com
  tasks:
    - name: List directory
      sudo: yes
      shell: ls
      
    - name: Run common setup script on web servers
      sudo: yes
      shell: /src/Install-Scripts/common.sh
