
- name: provision "{{ tag }}" servers
  ec2:
    key_name: devops
    region: us-west-2
    instance_type: "{{ type }}"
    image: "{{ ami }}"
    wait: true
    count: "{{ count }}"
    instance_tags:
      type: "{{ tag }}",
      type: "reddit"
