
- name: Create servers for site
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Provision web server
    ec2:
      key_name: devops
      region: us-west-2
      instance_type: t2.micro
      image: "ami-5189a661"
      wait: true
      exact_count: 1
      count_tag:
        type: webserver
      instance_tags:
        type: webserver
    register: webservers
  - name: Provision a set of instances
    ec2:
      key_name: devops
      region: us-west-2
      instance_type: t2.micro
      image: "ami-5189a661"
      wait: true
      exact_count: 1
      count_tag:
        type: queue
      instance_tags:
        type: queue
    register: queueservers
  - name: Provision a set of instances
    ec2:
      key_name: devops
      region: us-west-2
      instance_type: t2.micro
      image: "ami-5189a661"
      wait: true
      exact_count: 1
      count_tag:
        type: postgres
      instance_tags:
        type: postgres
    register: postgresservers
  - name: Provision a set of instances
    ec2:
      key_name: devops
      region: us-west-2
      instance_type: t2.micro
      image: "ami-5189a661"
      wait: true
      exact_count: 1
      count_tag:
        type: haproxy
      instance_tags:
        type: haproxy
    register: proxyservers
  - name: Provision a set of instances
    ec2:
      key_name: devops
      region: us-west-2
      instance_type: t2.micro
      image: "ami-5189a661"
      wait: true
      exact_count: 1
      count_tag:
        type: cassandra
      instance_tags:
        type: cassandra
    register: cassandraservers
