- name: terminate all reddit instances
  hosts: tag_type_reddit
  gather_facts: false
  tasks:
    - name: 
      local_action:
          module: ec2
          state: 'absent'
          region: us-west-2
          instance_ids: '{{ec2_id}}'
