- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Get instance info
      action: ec2_facts
      register: ec2
      
    - name: Terminate instances that were previously launched
      ec2:
        state: 'present'
        instance_ids: '{{ ec2.instance_ids }}'
